apiVersion: v1
kind: Service
metadata:
  name: productpage
  labels:
    app: productpage
    service: productpage
spec:
{{ include "bookinfo.ports" . | indent 2 }}
  selector:
    app: productpage
---
